version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - fatcontext
    - gochecksumtype
    - gocritic
    - gosec
    - gosmopolitan
    - loggercheck
    - nilnesserr
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - zerologlint
    - makezero
    - noctx
    - nilerr
    - errorlint
    - unused
  disable:
    - errchkjson #TODO: enable me
    - perfsprint #TODO: enable me
    - contextcheck
    - err113
    - exhaustive
    - gocheckcompilerdirectives
    - musttag
    - unparam
    - wrapcheck
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - rangeValCopy
        - exitAfterDefer
        - elseif
        - dupBranchBody
        - assignOp
        - singleCaseSwitch
        - captLocal
        - commentFormatting
        - ifElseChain
        - sprintfQuotedString
        - commentedOutCode
        - preferFprint
        - importShadow
        - emptyStringTest
        - paramTypeCombine
        - unnamedResult
      enabled-tags:
        - performance
        - diagnostic
        - style
      settings:
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        underef:
          skipRecvDeref: true
    govet:
      disable:
        - deepequalerrors
        - fieldalignment
        - shadow
        - unsafeptr
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - golint
        text: should be
      - linters:
          - errcheck
        text: not checked
      - linters:
          - staticcheck
        text: SA(1019|1029|5011)
      - linters:
          - gocritic
          - gosec
          - unused
        path: test\.go
      - linters:
          - gocritic
          - gosec
          - unused
        path: hack\.go
      - linters:
          - gocritic
          - gosec
          - unused
        path: cmd/devp2p
      - linters:
          - gocritic
          - gosec
        path: metrics/sample\.go
      - linters:
          - gocritic
          - gosec
        path: p2p/simulations
      - linters:
          - gocritic
          - gosec
        path: p2p/dnsdisc
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
